node {

  checkout scm

  sh "git rev-parse --short HEAD > commit-id"

  tag = readFile('commit-id').replace("\n", "").replace("\r", "")
  appName = "nickbot"
  registryHost = "127.0.0.1:30400/"
  imageName = "${registryHost}${appName}:${tag}"
  env.BUILDIMG=imageName

  stage "Build"

    sh "docker build -t ${imageName} -f nickbot/Dockerfile nickbot"


  stage "Push"

    sh "docker push ${imageName}"

  stage "Deploy"

    sh "sed 's#127.0.0.1:30400/nickbot:latest#'$BUILDIMG'#' nickbot/k8s/deployment.yaml | kubectl apply -f -"
    sh "kubectl rollout status deployment/nickbot -n nickbot"

  }
