
  podTemplate(label: "Template",
  containers: [containerTemplate(name: 'docker', image: 'docker:1.11', ttyEnabled: true, command: 'cat')],
  volumes: [hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock')]) {

    node("Node") {
        tag = readFile('commit-id').replace("\n", "").replace("\r", "")
        appName = "nickbot"
        registryHost = "127.0.0.1:30400/"
        imageName = "${registryHost}${appName}:${tag}"
        env.BUILDIMG=imageName
        checkout scm
          stage('Build Docker image') {
            container('docker') {
              sh "docker build -t ${image} ."
              }
          }
          stage('Push Docker image') {
            container('docker') {
              sh "docker push ${imageName}"
              }
          }
          stage('Deploy Docker image') {
            container('docker') {
              echo "hello"
              }
          }




      }
  }
